SELECT
    STATION AS station_id,
    "NAME" AS "name",
    LATITUDE AS latitude,
    LONGITUDE AS longitude,
    ELEVATION AS elevation,
    CAST("DATE" AS DATE) AS "date",
    AWND AS avg_wind,
    AWND_ATTRIBUTES AS awnd_attr,
    PRCP AS precipitation,
    PRCP_ATTRIBUTES AS precipitation_attr,
    SNOW AS snow,
    SNOW_ATTRIBUTES AS snow_attr,
    SNWD AS snow_depth,
    SNWD_ATTRIBUTES AS snow_depth_attr,
    TMAX AS temp_max,
    TMAX_ATTRIBUTES AS temp_max_attr,
    TMIN AS temp_min,
    TMIN_ATTRIBUTES AS temp_min_attr,
    WDF2 AS wind_dir_2,
    WDF2_ATTRIBUTES AS wind_dir_2_attr,
    WDF5 AS wind_dir_5,
    WDF5_ATTRIBUTES AS wind_dir_5_attr,
    WSF2 AS wind_speed_2,
    WSF2_ATTRIBUTES AS wind_speed_2_attr,
    WSF5 AS wind_speed_5,
    WSF5_ATTRIBUTES AS wind_speed_5_attr,
    WT01 AS fog,
    WT01_ATTRIBUTES AS fog_attr,
    WT03 AS thunder,
    WT03_ATTRIBUTES AS thunder_attr
FROM {{ ref('weather') }}